test_that("get_seq retrieves sequences and creates GRanges object", {
  
  dat <- data.frame(
    contig = c("chr11", "chr13"),
    start = c(108510788, 75803913),
    end = c(108510791, 75803916),
    gene = c("GeneA", "GeneB"),
    transcription_status = c("genic", "intergenic")
  )
  
  gr <- get_seq(species = "human", genome_version = "GRCh38", regions_df = dat)
  
  # Check if the result is a GRanges object
  expect_true(is(gr, "GRanges"))
  
  # Check if the extra metadata columns are retained
  expect_identical(gr$gene, regions_df$gene)
  expect_identical(gr$transcription_status, regions_df$transcription_status)
  
  # Check if the sequence data is added to the GRanges object
  expect_identical(as.character(gr$sequence), c("GTTT", "AGAA"))
})
#############################################################################
test_that("get_seq retrieves the same seq as mouse mutagenesis panel chr1.2", {
  
  dat <- data.frame(
    contig = "chr1",
    start = 155235938,
    end = 155238338)
  
  gr <- get_seq(species = "mouse", genome_version = "GRCm38", regions_df = dat)
  
  # Check if the result is a GRanges object
  expect_true(is(gr, "GRanges"))
  
  # Check if the sequence data is added to the GRanges object
  expect_identical(as.character(gr$sequence),
"CAATCTCCAGGATGCAGCCAGGGAAGGGAGAGTATGCAGCAGGCAGAGGGCTCTAAAGCCTTTGCTTGGCGTTCATTTGTTTATATTAAAGCTTTGACAGTCGAGGACAGAGATCGTTACTATTGCTGTCTGAGGGAGGGAGGAAGGAGAGTGGTTTGTGAAGGTGCACCGTTCTTGAGTCCATAGGACACCCACAGAATGAAACCTAACGAAATGGGTTACAGTGGGCTTCAAGGAATCCCCACTCCTGGACCATCCCTTCCCAGAAGTATCACCCAGTGAGTGCCTTCAGGGCTAAGCCTCAGTTTCCTCATAGGCTCATAGGGCTCAGCTGTTAAGAGAAACTGTCCCTCCAAACACAGTAAGATTCCACAAACTGTTATTAGTCCTAGTGTTACCCCCGCCCCTTCTCTCTCCCTCTTACTTCGGGACTGCAAGTGCACAGCTTTCTTTGTCTCTGTATCTACATGGTGCAGGATAAGGGCAATGGTGGGAGGGGGGGTAAGGTCACCTGCCAACGAGGCTACACTGCTGCTGGCAAAGAGAAGGCCTGTTTAGAAGTGACGTCAGTGTGCAGCTTGAGAGGGCCTACAGGGTTTGTTCCAGACTTTCAAAAGCCTCTGATGAGCTCTGTGGAAAAGGTGACTTCCACTGCACAGGGGACAGGAGGCTGCTGATGGGGAGCAGAGGAAGGCCAATGCCCTTCTCTCCACAGAGAGGGCAGACCAGCTCTGTCCATGTTCCCGAAGAATGATAACACATTCCCCACTGAGGCCCAGAACATGGCCAGGTCAGCATGGCATGGGCTCAGTACGGGCACACAGACAGCTGGTGTGGCAGATGTCTGAGACACTCCCAGAAGGGACTTTTCTGGAGGTCAGCTTAGCTCCCTCCCACCTTGAAGATGTTAACTTCAGTGAGCTCCTCCCAGCTCAGGGCTGAGGCACGAAAGGATTCGGTGTGTGGAGTGGCTGTGGGTGTGGTGACAAGCGCAGCAAGGGACCAAGCACCGGAGCCTTCCAAAGCACTGGCTTTGTGTGGGATCAACCCAGGGAGCAGAGTCCTGGACGCCACGGAAACGGTGAAGCATTTACAGCATTTAGAGGCTTGATGCACGGCTTGGCTGTTTTGTCCTTTTTCCTTTGAGCATCTTGGGACTGCAAGTGCAGAGCTTTCTTTGTCTCTGTATCTGCACAGTACAAGATAAGGGCGATGGTGGGAGGGGGGATAAGCCAGCAACATGGGGTACAACCTCTCCAGTGACATCTTGCCCTGGGCACTCCTCGTTGACCGCTGTGACCCCAAAATGCCCAATGACTCATCCTCTAGGCTAGGGAACCAAATCCCTGTCACTCTAGGCTCAAAAGATACAAAAAATGGCCAGTGGCTGGCTCAAGATGGCCTCTTTCTGGGCTCCTCGAAGCTGCTTGGCCCACAGGACTCACACCAGTCAATTTCCAGCAGATAAGATCATCCTTTTGTGTAGGAGGAGGCAGCGGGAACAGGAAGGAGACTGTTGAATGCCTCTGCATCCAAATGAGATCTCAGTTCCAGGCTCTCCCCGGGCAGCTCCCCTCCACGGATCACCACACACCCCACCTCAGATGAAGCATTGCTGCAGCCTCCCTCACCCATCTGGAATGTTCCTTCTGTTTCCACCCAGACCCTTGCAAGCCCTCACAGGCTCCAGCTGTCGGAGAGCCCTCAGTCAGCTCTTTCCTGCCTGCCTTAGCCAGACACGCTATGAGCACCTGTTCTAAAAAGGCACAGCTCCTGCCTCCAGGAACTCAAGGAGAAAGACGCCCGTAATGGCATTGGTGGCAGTGGTGGCCGGCGGGGCCGGCGGGCAGAGCCATGAGAACAAAGCAGGTGATTCCATTTGAAAGCACAGACACACAAGCTGACTCATGCGTCTCTCACTTCCCACAGCAGAGAACAGATCGATCTGCAGGACATAGAAGGCCCCAGATCCCCAGCCCGAGGGGTTGCTTATCCAAGGGATGACCTGTGGAGGTATGAAAAGGGTAGCTCAAGGCAGTGTCCCATAGCAGTCAGAGCATAAGCCTGGGACCCGAGTGCAAGTCCTGACTCCAAGACTTGGCCTCCCCTAGAGTGCTCTCTGTCCTCGAAGCAAGAACAATGGCTGAGACCTGTCCACAAAGTGAGATGTACAAACAGCACTTACACAGCACCCGGCACACAGGCAGGGGATGGAAATGGCAGATGCCAGCCTGCTCTTCCAACAGGCCACTAGTGTCTTAGCCAATGCGTGCTAGAGAACAACCCTTGGGGTAAGGGGACAAAGGTCTCCTGCAGGATCTGAGGTCCTGAGTCTTTAGGTGGCTCACCTCAAGGCTACCTTGTAACAGGCTGGCCCAGACACTGCAGACTCAAGCACTGG"
)
})

  