params:
# Set up Info
  projectdir: NULL # The  working directory for file paths. If null, will use the current working directory.
  outputdir: NULL # The output Directory. If null, will use the project directory.
  project_title: MutSeqR Analysis # The Project Title
  researcher_name: FirstName LastName # The name of the lead researcher
  user_name: FirstName LastName # The name of the one running the analysis
  project_description: This is an example of the Rmd Summary report generation # Optional description of the project.
# Profile
  config_profile: "Duplex Sequencing Mouse Mutagenesis Panel" # Use a pre-defined Parameter Configuration File: Options: Duplex Sequencing Human Mutagenesis Panel, Duplex Sequencing Mouse Mutagenesis Panel, Duplex Sequencing Rat Mutagenesis Panel, None
# Data Import:
  species: "mouse" # The species of the model organism.
  genome: "mm10" # The reference genome.
  file_type: "table" # Format of the mutation data to be imported: table or vcf.
  mutation_file: "file/path/to/mutation/data" # The file path to the mutation data. Directory or single file.
  mut_sep: "/t" # The delimiter for importing mutation data in table format. Default is tab-delimited.
  sample_data: "file/path/to/sample_data.txt" # The file path to the sample metadata.
  sd_sep: "/t" # The delimiter for importing the sample metadata. Default is tab-delimited.
# Calculating MF
# Precalculated depth data is only required for mutation data that does not contain total_depth or depth values for every sequenced site.
  precalc_depth_data_global: Null # The file path to the precalculated per-sample total_depth data. This is the total number of bases sequenced per sample, used for calculating mutation frequencies. Columns are "sample" and "group_depth".
  precalc_depth_data_base6: Null # The file path to the precalculated per-sample total_depth data in the base_6 context. This is the total number of C and T bases sequenced for each sample. Columns are "sample", "normalized_ref", and "subtype_depth". If using an exp_variable, please also include it in this table.
  precalc_depth_data_base96: Null # The file path to the precalculated per-sample total_depth data in the base_96 context. This is the total number bases sequenced per sample for each of the 32 possible trinucleotide contexts in their pyrimidine notation. Columns are "sample", "normalized_context", and "subtype_depth". If using an exp_variable, please also include it in this table.
  precalc_depth_data_rg: Null # The file path to the precalculated per-sample total_depth data for each target region. This is the total number of bases sequenced per sample for each region. Columns are "sample", 'region_col', "group_depth". Only applicable if performing  regions analysis.
  d_sep: "\t" # The delimiter for importing the the precal_depth_data_global. Default is tab-delimited. This will be the same for all precalc-depth-data.
# Statistical Analysis
  exp_variable: "dose" # experimental variable. Example chemical dose (levels 0, 12.5, 25, 50 mg/kg-bw/d).
  exp_variable_order: [0, 12.5, 25, 50] # Vector. The levels of the experimental variable in the desired order. For plotting purposes.
  reference_level: 0 # The reference level of your experimental variable. Ex. the vehicle control for dose groups.
  contrasts: "file/path/to/contrasts.txt" # The contrasts table specifying pairwise comparisons between levels of the experimental variable. Requires 2 columns, no header.
  cont_sep: "\t" # The delimiter for importing the contrasts table.
  bmd: TRUE # A logical variable indicating whether to run a BMD analysis. Assumes the exp_variable is dose/concentration (numeric).
  bmr: 0.5 # The benchmark response for the bmd analysis. Defined as a bmr-% increase in MF from the reference level.
  bmd_method: "proast" # Options: "proast", "toxicr" The method for running the bmd analysis.
  num_boots: 200 # The number of bootstraps to run for PROAST model averaging. 200 is recommended but may reduce to 50 to decrease run time.
# Signature Analysis
  run_sigfitting: TRUE # A logical variable indicating whether to run signature_fitting. Will create a virtual environment to run python on first use.
  python_version: 3.11 # The python version for signature fitting
# If not using a pre-defined contig_profile, fill out the params for a custom profile:
Custom_Profile_Params:
  ecs_technology: Duplex Sequencing
# Import Paramaters
  is_0_based_mut: TRUE # A logical variable indicating whether the genomic coordinates of the mutation data are 0-based (TRUE) or 1-based (FALSE).
  regions: NULL # Optional file path to the regions metadata file.
  is_0_based_rg: TRUE # A logial variable indicating whether the genomic coordinates of the regions metadata file are 0-based (TRUE) or 1-based (FALSE).
  rg_sep: "/t" # Delimiter for importing tabular mutation data.
# Filtering Parameters
  vaf_cutoff: 1 # Numeric values from 0-1. Flag variants with a VAF > vaf_cutoff for filtering (germline variants).
  snv_in_germ_mnv: FALSE # Flag SNVs that overlap with germline MNVs for filtering.
  rm_abnormal_vaf: FALSE # Remove records where the VAF is between 0.05-0.45, or between 0.55-0.95.
  custom_filter_col: NULL # Apply a custom filter to the specified column.
  custom_filter_val: NULL # The value in custom_filter_col by which to filter.
  custom_filter_rm: FALSE # A logical variable indicating whether records that contain the custom_filter_val within the custom_filter_col should be removed (TRUE) or flagged (FALSE).
  filtering_regions: NULL # Optional file path to regions file by which to filter variants. Must contain the contig, start, and end of each region. The file path will be read as projectdir/filtering_regions.
  filtering_rg_sep: "\t" # The delimiter for importing the filtering_regions file.
  regions_filter: "keep_within" # "keep_within" will remove any records that fall outside of the filtering_regions. "remove_within" will remove records that fall inside of the filtering_regions.
  allow_half_overlap: FALSE # A logical variable indicating whether to include records that half overlap with the regions. If FALSE, the start and end position of the record must fall within the region interval to be counted as "falling in the region". If TRUE, records that start/end within the region interval, but extend outside of it will be counted as "falling inside the region".
  filtering_is_0_based_rg: TRUE # A logical variable indicating whether the genomic coordinates of the filtering_regions are 0-based (TRUE) or 1-based (FALSE).
  rm_filtered_mut_from_depth: TRUE # A logical variable indicating whether the alt_depth of variants flagged during the filtering process should be removed from their total_depth values. This does not apply to records flagged as germline variants.
# Statistical Analysis
  do_regions_analysis: TRUE # A logical variable indivating whether to perform Generalized Linear Mixed Modeling of the data by sequencing target. This is applicable to data sets that used a targetted panel or has specific regions of interest.
  region_col: label # The column name that uniquely identifies each target region for the regions_analysis. This column must be present in the mutation_data or in the regions metadata file.