name: Build PDF Manual

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.pdf'  # This prevents the workflow from running when a PDF file is committed

jobs:
  build_manual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Build PDF manual
        run: |
          R CMD Rd2pdf
          # Rscript -e 'devtools::build_manual(pkg = ".", path = ".")'

      - name: Commit PDF Manual
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *.pdf
          git commit -m "[skip ci] Update PDF manual" -a || echo "No changes to commit."
          git push || echo "No changes to push."
