# .github/workflows/build-manual.yml
name: Build and Commit PDF Manual

on:
  push:
    branches:
      - main
    # Only run if .R or .Rd files change, not on other changes.
    paths:
      - 'R/**'
      - 'man/**'

jobs:
  build_manual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texinfo

      - name: Create inst/doc directory
        # The -p flag ensures it doesn't fail if the directory already exists.
        run: mkdir -p inst/doc

      - name: Build PDF manual
        run: |
          R CMD Rd2pdf . --output=MutSeqR.pdf

      - name: Commit PDF Manual
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add inst/doc/MutSeqR.pdf
          git commit -m "docs: Rebuild PDF manual [skip ci]" || true
          git push || true