# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Patch vignette YAML for pkgdown rendering
        run: |
          ls -al
          pwd
          find . | grep Rmd
          awk '
            BEGIN { in_output = 0 }
            /^output:/ {
              print "output:\n  rmarkdown::html_document:\n    toc: true\n    toc_float: yes\n    code_folding: show\n    code_download: yes\n    css: custom.css"
              in_output = 1
              next
            }
            in_output && /^\S/ { in_output = 0 }
            !in_output { print }
          ' vignettes/MutSeqR_introduction.Rmd > tmp && mv tmp vignettes/MutSeqR_introduction.Rmd

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgsl-dev

      - name: Install GitHub-only dependencies
        run: |
          Rscript -e 'install.packages("remotes", repos = "https://cloud.r-project.org")'
          Rscript -e 'remotes::install_github("AlexandrovLab/SigProfilerMatrixGeneratorR")'
          Rscript -e 'remotes::install_github("NIEHS/ToxicR")'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          dependencies: '"hard"'
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
